### ISSUE TITLE
How can i add a client from UI and how to add version to the secret?

### ISSUE THREAD

**Issue by hshyamh4** [square/keywhiz#112]

**Comment by sul3n3t** [comment]
Right now, clients are added via the `/automation/clients` [API endpoint](https://github.com/square/keywhiz/blob/master/server/src/main/java/keywhiz/service/resources/AutomationClientResource.java#L145). This is definitely a step that's preferable to automate. We could add that ability back to the UI, but it's not there currently.

To answer your second question, when you add a secret it has a set (name, version) pair. The intent is that multiple secrets can be added with the same name, but have multiple versions. Versions are generated. For example, `keywhiz.cli add secret --name somefile.txt --with-version < somefile.txt`
