### ISSUE TITLE
how to access the service '/automation/secrets' with name

### ISSUE THREAD

**Issue by hshyamh4** [square/keywhiz#114]
I gone through the link http://square.github.io/keywhiz/apidocs/#!/secrets-admin/createSecret 
and found

![screenshot from 2015-06-10 18 58 57](https://cloud.githubusercontent.com/assets/12181092/8083570/336b22be-0fa3-11e5-8afb-c31d1b5f1d30.png)

It is mentioned as 'Implementation Notes
'Returns a single secret or a set of all secrets'

So i want to access this service by name.

**Comment by sul3n3t** [comment]
You can make a request to `/automation/secrets?name=<secret name>`. [Here's the method](https://github.com/square/keywhiz/blob/master/server/src/main/java/keywhiz/service/resources/AutomationSecretResource.java#L139).

**Comment by hshyamh4** [comment]
This service is working fine for secrete without version secretes.How can i make it works for version with version ?

**Comment by sul3n3t** [comment]
For 1) what is the URL? It says 404, but not where your request went.

For 2) The error is coming from your method and it's deserializing JSON to the wrong type. Keep in mind `/secret/<secret_name>` and `/automation/secrets?name=<secret_name>` are different endpoints with different JSON responses. `GET /automation/secrets?name=<secret_name>` returns `List<AutomationSecretResponse>`.
