### ISSUE TITLE
Is it possible to create a secret only using keywhiz api

### ISSUE THREAD

**Issue by hshyamh4** [square/keywhiz#118]
As per #82,
To  consume a service /secret/{secretName}, It should have client and groups,
I do not want to create groups and clients.
Even i can consume service  /secret/{id} without having groups and clients to that secret.

Like wise,I just want to create secret and consume it by  /secret/{secretName}.

**Comment by sul3n3t** [comment]
When a client and a secret share at least one common group, that is what authorizes the client to access a secret. Secrets and clients can exist in Keywhiz without group assignments, but the client will not be able to access the secret. If that were allowed, there would be no access control between different clients.
