### ISSUE TITLE
Migrate to JOOQ

### ISSUE THREAD

**Issue by riyazdf** [square/keywhiz#12]
JDBI is getting relatively painful to use for keywhiz due to complexity and verbosity (see [AclDAO.java](https://github.com/square/keywhiz/blob/master/server/src/main/java/keywhiz/service/daos/AclDAO.java#L226)).  

We've used JOOQ for some DAO tests and it'd be nice to move everything to JOOQ and keep things uniform.

**Comment by alokmenghrajani** [comment]
r.i.p. jdbi.

It might be worth posting in the google group explaining why we did this. Maybe also give people a heads up in case they run into any issues related to these changes?
