### ISSUE TITLE
Help needed for consuming /secret/{secret name}

### ISSUE THREAD

**Issue by hshyamh4** [square/keywhiz#120]
Hi @sul3n3t ,
I want to create group,client and assign them each other.Create secret and grant access to previously created client and group,Consume secret  it by /secret/{secret name} service.

Related to #82

Everything using java and keywhiz api.

Please do help me.

**Comment by sul3n3t** [comment]
Unclear what the problem is. This sounds like a discussion question for the mailing list and not a github issue.
