### ISSUE TITLE
How to customize keywhiz server to authenticate with username and password to consume any service ? 

### ISSUE THREAD

**Issue by hshyamh4** [square/keywhiz#122]
I want to consume a service which has to give me a secret by taking a user name and password.

**Comment by sul3n3t** [comment]
Reading secret content by authenticated with a password is not supported.

**Comment by hshyamh4** [comment]
@sul3n3t 

If i want to customize keywhiz to authenticate username and password for consuming a secret,then what and where i need to customize the application ?

**Comment by sul3n3t** [comment]
It's not currently supported to access secret content with a username/password combination. I recommend using strong authentication, like client certificates.

However, you can customize and add something that will do that. Create your own REST endpoint, similar to `keywhiz.service.resources.SecretDeliveryResource`, which is pretty simple. Register them with jersey in an `io.dropwizard.Bundle`. Lastly, register your custom bundle with Keywhiz:

```
KeywhizService keywhizService = new KeywhizService();
Command serverCommand = new ServerCommand<>(keywhizService);
Bootstrap<KeywhizConfig> bootstrap = new Bootstrap<>(keywhizService);
bootstrap.addCommand(serverCommand);
bootstrap.addBundle(someCustomBundle);
keywhizService.initialize(bootstrap);
serverCommand.run(...)
```
