### ISSUE TITLE
Login for development 

### ISSUE THREAD

**Issue by carlskii** [square/keywhiz#152]
Hi, 

I just loaded the dev data and started the Keywhiz server and tried logging in with keywhizAdmin:adminPass. This does not seem to work. Are these the correct credentials ?

**Comment by mcpherrinm** [comment]
Those are the correct credentials, inserted when you run the "java -jar keywhiz-server*jar db-seed config.yaml" command.  Does db-seed work?  Are you trying to log in with the command line, or the web UI?

**Comment by carlskii** [comment]
Yes I ran this it seemed to work OK: 

java -jar server/target/keywhiz-server-*-SNAPSHOT-shaded.jar db-seed server/src/main/resources/keywhiz-development.yaml

**Comment by carlskii** [comment]
OK Strange - ran it again and it worked. Thanks.
