### ISSUE TITLE
Instructions around db-seed data are unclear

### ISSUE THREAD

**Issue by alexcole** [square/keywhiz#166]
The docs say "(Optional) Import some development data:" but it seems like if you fail to do this you can't log in with the dev username/password. I just wasted a bunch of time trying to figure our what the username/password was because I failed to run db-seed. I think the instructions should be explicit that this is really necessary to set up the dev account.

**Comment by alokmenghrajani** [comment]
Agree. We should perhaps render some banner in the web UI saying the database is empty.

**Comment by viniciusccarvalho** [comment]
I can't still get it working. I ran the db-seed, I've opened the DB using H2 console, and I can see the keywhizAdmin user, and a hashed password, but trying the adminPass password yield a User authentication failed at login for keywhizAdmin

**Comment by viniciusccarvalho** [comment]
Hum, it does not work on Chrome, tried it on firefox and it works ...

**Comment by mcpherrinm** [comment]
Not working on Chrome is very strange!  I do all my development on Chrome; it certainly WFM.  Do you think you could try to capture the two requests to the Keywhiz server from the browsers and file a bug against Keywhiz?

**Comment by viniciusccarvalho** [comment]
My bad, I had a couple of plugins in chrome messing with cookies and headers, it worked on incognito mode. 
Sorry about that

**Comment by alokmenghrajani** [comment]
Glad to hear it now works.

**Comment by mcpherrinm** [comment]
I've added a command to explicitly add a user.  I'll follow up with some new docs tomorrow that explicitly set up a user instead of relying on db-seed in https://github.com/square/keywhiz/pull/171
