### ISSUE TITLE
Remove non-mysql database support

### ISSUE THREAD

**Issue by mcpherrinm** [square/keywhiz#291]
Our build systems are overly complicated by our (not great) way of supporting multiple database engines.

I think we should remove postgres/h2, and check in the jooq generated Java.

That'll simplify building a lot.  If there's somebody who wants to support another database later, then we could consider re-adding databases.

There will be additional burden on any developers making new migrations, because they'll have to check in the generated code, but we can provide a script to ensure that's done properly.

**Comment by mcpherrinm** [comment]
Postgres has been removed

**Comment by mbyczkowski** [comment]
H2 has been removed in #444.
