### ISSUE TITLE
API docs cannot be found.

### ISSUE THREAD

**Issue by tom-schultz** [square/keywhiz#325]
I'm evaluating Keywhiz and I can't access the API docs through the github pages site.

**Comment by mcpherrinm** [comment]
Looks like they broke when we moved off using the "gh-pages" branch.  (Javadocs & swagger are missing).

It should be a pretty easy fix - we just need to regen javadocs and swagger and check them back in.  I'll try to get to that soon.

**Comment by tom-schultz** [comment]
Great, thanks.

**Comment by kiananthagn** [comment]
@mcpherrinm Any idea when this will be fixed? 
Thanks in advance.

**Comment by csstaub** [comment]
Just fixed these: https://square.github.io/keywhiz/apidocs
