### ISSUE TITLE
HTTP ERROR 404

### ISSUE THREAD

**Issue by GoodHaHa** [square/keywhiz#328]
When I open https://localhost:4444/ , I get this error：

```
HTTP ERROR 404

Problem accessing /. Reason:

    Not Found
Powered by Jetty://
```

**Comment by mcpherrinm** [comment]
There's nothing expected to be there.  Is there documentation somewhere that suggests otherwise?

**Comment by mcpherrinm** [comment]
docs cleaned up in https://github.com/square/keywhiz/pull/329

**Comment by kaido89** [comment]
There is some reference on the Dockerfile:

` `# After keywhiz starts up, you can access the admin console by going
` `# to https://[DOCKER-MACHINE-IP]/ui in your browser. The default user
` `# in development is keywhizAdmin and the default password is adminPass.

Which still give the same error HTTP ERROR 404, when opening the https://[DOCKER-MACHINE-IP]/ui.

**Comment by GoodHaHa** [comment]
@kaido89 The latest version has already remove the ui.

If you want to run a example, you can look at [keywhiz-env](https://github.com/gyulaweber/keywhiz-env) and use the previous version.

**Comment by csstaub** [comment]
Yep, that's a documentation error, the UI has been removed. I can update the Dockerfile to remove reference to it.

**Comment by csstaub** [comment]
Updated docs in #342

**Comment by kaido89** [comment]
Hi may I also ask where I can find API documentation? Is is present in any previous build?

**Comment by csstaub** [comment]
Can be found here: https://square.github.io/keywhiz/apidocs

Internally, Square uses keywhiz-fs (https://github.com/square/keywhiz-fs) and is also developing keysync as the next-gen client (https://github.com/square/keysync)
