### ISSUE TITLE
HTTP ERROR 401 error

### ISSUE THREAD

**Issue by kaido89** [square/keywhiz#343]
Hi I would to question if the browser is intended to not allow the client to access this webpage:
https://localhost:4444/admin/secrets
This was I got on the browser
`HTTP ERROR 401`
`Problem accessing /admin/secrets. Reason:`
   `Unauthorized`
`Powered by Jetty://`
This was I got the server
`INFO  [2017-06-01 15:59:30,199] keywhiz.auth.xsrf.XsrfServletFilter: Request missing X-XSRF-TOKEN header`
`0:0:0:0:0:0:0:1 - - [01/Jun/2017:15:59:30 +0000] "GET /admin/secrets HTTP/1.1" 401 303 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" 84`

PS: Since now UI has been removed what are the ways to access the secrets, because from my understanding keywhiz-fs project will be stopped, there isn't browser mode, and client does not allow to access the secret?

**Comment by csstaub** [comment]
The old keywhiz web UI was deprecated and removed, accessing through a browser won't work.
