### ISSUE TITLE
One possible mac.init error

### ISSUE THREAD

**Issue by wanghs09** [square/keywhiz#365]
In the function Hkdf.java/ extract(@Nullable SecretKey salt, byte[] ikm) 
`Mac mac = initMac(salt);`
`byte[] keyBytes = mac.doFinal(ikm);`

Should it be 
`Mac mac = initMac(ikm);`
`byte[] keyBytes = mac.doFinal(salt);`
?

**Comment by csstaub** [comment]
What makes you think that it's a mistake? It looks correct to me, and matches RFC 5869.

**Comment by alokmenghrajani** [comment]
I'm going to close this out. We don't actually use the `extract` method.

https://github.com/square/keywhiz/blob/master/server/src/main/java/keywhiz/service/crypto/ContentCryptographer.java only calls `expand`.
