### ISSUE TITLE
Key Rotation

### ISSUE THREAD

**Issue by cocowalla** [square/keywhiz#373]
The [Medium article about Keywhiz](https://medium.com/square-corner-blog/protecting-infrastructure-secrets-with-keywhiz-af674410832f), from when it was open sources in 2015, makes brief mention of key rotation. I can't find anything related to it in this repo though - does Keywhiz have any features to support key rotation?

**Comment by mcpherrinm** [comment]
Keywhiz supports versioned secrets which can be updated via API or
administrator CLI.  Keysync automatically and routinely downloads updated
secrets.  Keywhiz can also store expiry dates of each version of a secret,
which can be used by API clients to decide to replace a private key and
renew a certificate, for example.
