### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [square/keywhiz#375]
Greetings @square-sdk-deployer  @square ,

I was passing by (this repository) and tought I'd like to collaborate by proposing a logo
if that's something that may interest you! let me know!

I'm a Graphic Designer and an Open Source enthusiastic
looking to improve my portfolio and collaborate to really cool projects like this one!

Best Regards,
-Luigi.

**Comment by mcpherrinm** [comment]
Hi Luigi.  We've always wanted a logo for Keywhiz, and I would definitely like to collaborate.

My team's other popular open source projects include github.com/square/certigo, github.com/square/certstrap, and github.com/square/ghostunnel -- if you'd prefer to make a logo for one of them instead, that would be great too.

What would you like from us to help you out?

**Comment by LuigiBaute** [comment]
Hi @mcpherrinm ,

Before proceeding towards the logo-making process I'll give you some questions that would help us create a wonderful logo that suits this project best.

What's the name that should be displayed on the logo/icon ?

What's the purpose/goal of this project ? (details of the project can work too)

What's the message you would like the logo/icon to transmit?

I'll be looking forward to your reply! hopefully something good can come out of this work!

**Comment by mcpherrinm** [comment]
We talked internally and our trademark/brand people aren't really sure how contributed logos would work, so we don't plan to figure this out right now.
