### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [square/keywhiz#422]
Hi
The following lines have cryptographic API misuses. <br> File name => hkdf/src/main/java/keywhiz/hkdf/Hkdf.java: Line number => 103: API name => SecretKeySpec:<BR> File name => hkdf/src/main/java/keywhiz/hkdf/Hkdf.java: Line number => 98: API name => SecretKeySpec:<BR> File name => hkdf/src/main/java/keywhiz/hkdf/Hkdf.java: Line number => 103: API name => SecretKeySpec:<BR> File name => hkdf/src/main/java/keywhiz/hkdf/Hkdf.java: Line number => 98: API name => SecretKeySpec:<BR> File name => cli/src/main/java/keywhiz/cli/DevTrustStore.java: Line number => 30: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR>

**Comment by mcpherrinm** [comment]
Can you say more about what the "misuse" is?
