### ISSUE TITLE
Failed to execute goal org.flywaydb:flyway-maven-plugin:5.2.0:migrate

### ISSUE THREAD

**Issue by joaompinto** [square/keywhiz#423]
When attempt to build on Fedora30 with OpenJDK11 I get the following error:
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:5.2.0:migrate (default) on project keywhiz-model: org.flywaydb.core.api.FlywayException: Validate failed: Detected applied migration not resolved locally: 3 -> [Help 1]

**Comment by joaompinto** [comment]
[log.txt](https://github.com/square/keywhiz/files/3397893/log.txt)
Added build log file.

**Comment by via-justa** [comment]
I had the same issue right now, deleting the h2 DB and running again solved it for me (just started evaluating the product so no harm done)

**Comment by mbyczkowski** [comment]
Yes, there seems to be an issue with H2 DB after an update to flyway dependency. If you're still having issues @joaompinto just use Keywhiz with MySQL (`mvn install -P mysql`).

**Comment by mbyczkowski** [comment]
We have decided to drop H2 support (#444).
