### ISSUE TITLE
documentation links broken

### ISSUE THREAD

**Issue by via-justa** [square/keywhiz#425]
Hey, please note that a lot of the documentation links are not working. In general it looks like the tool documentation is very light for that size of a tool.

**Comment by mbyczkowski** [comment]
Yes, the public-facing documentation could use some clean-up. Is there something in particular that you find missing?

**Comment by via-justa** [comment]
Hey @mbyczkowski thanks for replying.
basically the entire bootstrapping process from both the server and client sides :) 

A bit of information about the background process so we'll know what to expect (and how to sale it to the mgmt) and some Q&A for knowen issues like the h2 flyway issue.

We like the concept very much but I cannot really implement it without having some documentation to work with.

Because the concept is so nice and fits like a glove to what we need that we decided to try and develop internally something with the same concept (in Go for the ease of it)

**Comment by mbyczkowski** [comment]
FWIW, we've been using Keywhiz in production for a few years now. The biggest change in recent years have been a move away from [Keywhiz-FS](https://github.com/square/keywhiz-fs) to using [Keysync](https://github.com/square/keysync).

The bootstrapping process is very Square-specific and it depends on how your infrastructure looks like. We're currently adopting [SPIFFE](https://spiffe.io/), so in the near future Keywhiz bootstrapping will be simplified if you're planning to use SPIFFE.

**Comment by alokmenghrajani** [comment]
If you write notes/docs on how to bootstrap, we'll be more than happy to review. Also, if you get stuck, we can help you debug things.

The docs live in https://github.com/square/keywhiz/tree/master/docs and PRs, even just small ones to fix broken links, are welcome.
