### ISSUE TITLE
how to retrieve secret using Web service call from java

### ISSUE THREAD

**Issue by hshyamh4** [square/keywhiz#82]
Hi,
I want to consume a secret from java api.when i try to consume it from RestClient then i am getting reply as unauthorized.  

Can you help how to do it.

**Comment by sul3n3t** [comment]
Do you mean the ruby (rest-client)[https://github.com/rest-client/rest-client]? Which API endpoint are you trying to access?

Endpoints under /admin require a user to login and get a cookie. Endpoints under /secret, /secrets, and /automation require a trusted client certificate.

**Comment by hshyamh4** [comment]
Rest client plugin of a chrome,I think it is asking for certificates, where can i get these certificates ?

**Comment by sul3n3t** [comment]
Assuming you're using the development/test secrets, there's a client [PKCS12 keystore here](https://github.com/square/keywhiz/blob/master/server/src/test/resources/clients/client.p12) and [PEM-encoded cert/key here](https://github.com/square/keywhiz-fs/blob/master/fixtures/client.pem).

**Comment by hshyamh4** [comment]
Hi sul3n3t,

I used curl command to retrieve secret by name,but it not working. 
curl --cert client.pem -k -H "Content-Type:application/json" https://localhost:4444/secret/Test

Then i got :
<p>Problem accessing /secret/CyberBank. Reason:
<pre>    Forbidden</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>


but when(below command) i secret by id ,it is working.
 curl --cert client.pem -k -H "Content-Type:application/json" https://localhost:4444/automation/secrets/1

So do i need to add any certificate than what i used earlier?

**Comment by sul3n3t** [comment]
`403 Forbidden` is returned when the client does not have authorization to read the secret. You can run `keywhiz.cli describe secret --name CyberBank` and you'll see the clients and groups that can access the secret.

I'm guessing you added the secret, but didn't assign it to a group. Running `keywhiz.cli describe client --name client`, you'll see the client certificate you're using is already in the 'Security' group. To give it access to your secret run `keywhiz.cli assign secret --name CyberBank --group Security`.

**Comment by hshyamh4** [comment]
I want to create group ,client using java(keywhiz) api and assign it to some secrete.
I can create secrete and group from UI but i can not create client.more over i can not assign clients to groups and groups to secrete.Can you help me how to create client  and group using java(keywhiz) api and assign it to secrete.

**Comment by sul3n3t** [comment]
What do you mean, you cannot 1) assign clients to groups and 2) assign groups to secrets? Are you getting an error message of some kind? Have you looked at the keywhiz-client module I linked?

**Comment by hshyamh4** [comment]
import io.dropwizard.jackson.Jackson;

import java.io.IOException;
import java.io.InputStream;
import java.security.KeyStore;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertificateException;

import javax.ws.rs.core.MediaType;

import keywhiz.AuthHelper;
import keywhiz.KeywhizService;
import keywhiz.api.AutomationSecretResponse;
import keywhiz.api.ClientDetailResponse;
import keywhiz.api.GroupDetailResponse;
import keywhiz.api.SecretDetailResponse;
import keywhiz.client.KeywhizClient;
import keywhiz.testing.HttpClients;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.common.collect.ImmutableMap;
import com.google.common.io.Resources;
import com.squareup.okhttp.OkHttpClient;

public class CreateGroupAndClient {

	public static void main(String[] args) throws IOException {
		KeywhizClient keywhizClient = keywhizClient();
		keywhizClient.login("keywhizAdmin", "adminPass".toCharArray());
		ClientDetailResponse createClient = keywhizClient.createClient("TestClient");//creating client
		GroupDetailResponse createGroup = keywhizClient.createGroup("TestGroup", "Cyber money test");//creating group
		keywhizClient.enrollClientInGroupByIds((int) createClient.id,(int) createGroup.getId());
		ImmutableMap<String, String> myMap = ImmutableMap.<String, String> builder().put("client", "client").put("group", "Security").build();
		SecretDetailResponse createSecret = keywhizClient.createSecret("TestSecret", "","TestSecret", true, myMap);
		keywhizClient.grantSecretToGroupByIds(Math.toIntExact(createSecret.id),Math.toIntExact(createGroup.getId()));//grant Secret To GroupByIds

		KeywhizClient retriveClient = mutualSslClient();
		AutomationSecretResponse secretDetailsById = retriveClient.getSecretDetailsByName("TestSecret");//calls httpGet(String.format("/secret/%s", secretName))
		System.out.println(secretDetailsById.secret());

	}

	public static KeywhizClient keywhizClient() {
		String password = "ponies";
		KeyStore trustStore = keyStoreFromResource(
				"dev_and_test_truststore.p12", password);

		OkHttpClient httpClient = HttpClients
				.builder()
				.addRequestInterceptors(
						new AuthHelper.XsrfRequestInterceptor("XSRF-TOKEN",
								"X-XSRF-TOKEN"),
						new AuthHelper.AcceptRequestInterceptor(
								MediaType.APPLICATION_JSON))
				.build(trustStore, 4444);

		com.fasterxml.jackson.databind.ObjectMapper mapper = KeywhizService
				.customizeObjectMapper(io.dropwizard.jackson.Jackson
						.newObjectMapper());
		return new KeywhizClient(mapper, httpClient);
	}

	private static KeyStore keyStoreFromResource(String path, String password) {
		KeyStore keyStore;
		try (InputStream stream = Resources.getResource(path).openStream()) {
			keyStore = KeyStore.getInstance("PKCS12");
			keyStore.load(stream, password.toCharArray());
		} catch (IOException | NoSuchAlgorithmException | CertificateException
				| KeyStoreException e) {
			throw new AssertionError(e);
		}
		return keyStore;
	}

	public static KeywhizClient mutualSslClient() {
		String password = "ponies";
		KeyStore keyStore = keyStoreFromResource("clients/client.p12", password);
		KeyStore trustStore = keyStoreFromResource(
				"dev_and_test_truststore.p12", password);

		OkHttpClient httpClient = HttpClients
				.builder()
				.withClientCert(keyStore, password)
				.addRequestInterceptors(
						new AuthHelper.AcceptRequestInterceptor(
								MediaType.APPLICATION_JSON))
				.build(trustStore, 4444);
		ObjectMapper mapper = KeywhizService.customizeObjectMapper(Jackson
				.newObjectMapper());
		return new KeywhizClient(mapper, httpClient);

	}


when i run above application the i am getting below error.
![screenshot from 2015-06-10 17 50 36](https://cloud.githubusercontent.com/assets/12181092/8082263/9482bf3a-0f99-11e5-98bb-64afc68e648b.png)

**Comment by sul3n3t** [comment]
I'm confused by your snippet. [keywhiz.client.KeywhizClient](https://github.com/square/keywhiz/blob/master/client/src/main/java/keywhiz/client/KeywhizClient.java) doesn't have a method `getSecretDetailsByName`.

**Comment by hshyamh4** [comment]
Hi @sul3n3t ,

method retriveClient.getSecretDetailsByName("TestSecret") is created by me in KeywhizClient like 
httpGet(String.format("/secret/%s", secretName))
```java
public AutomationSecreteResponseConcrete getAutomationSecretDetailsByName(String secretName) throws IOException {
	    String response = httpGet(String.format("/secret/%s", secretName));
	    return mapper.readValue(response, AutomationSecreteResponseConcrete.class);
  }
```

**Comment by sul3n3t** [comment]
I see. I commented in #118 about access control and group membership. Beyond that, you're using the wrong type for the response message. That method is [defined here](https://github.com/square/keywhiz/blob/master/server/src/main/java/keywhiz/service/resources/SecretDeliveryResource.java#L90) and returns a `SecretDeliveryResponse`.

**Comment by hshyamh4** [comment]
Thanks for your response,



I added group and client using keywhiz api.
```java
                KeywhizClient keywhizClient = keywhizClient();
		keywhizClient.login("keywhizAdmin", "adminPass".toCharArray());
		ClientDetailResponse createClient = keywhizClient.createClient("Client1");//creating client
		GroupDetailResponse createGroup = keywhizClient.createGroup("CyberMoneyTestGroup1", "Cyber money test1");//creating group
		keywhizClient.enrollClientInGroupByIds((int) createClient.id,(int) createGroup.getId());
```
then i created a Secrete,

```java
SecretDetailResponse createSecret = keywhizClient.createSecret("TestSecret1", "CyberMoney1","TestSecret1", true, ImmutableMap.of("",""));
```
i just granted secrete to the groups,
```java
keywhizClient.grantSecretToGroupByIds(Math.toIntExact(createSecret.id),Math.toIntExact(createGroup.getId()));
```

then i called service using,

```java
KeywhizClient retriveClient = mutualSslClient();
SecretDetailResponse secretDetailsById = retriveClient.secretDetailsForId((int)createSecret.id);
System.out.println(secretDetailsById.name);

public static KeywhizClient mutualSslClient() {
		String password = "ponies";
		KeyStore keyStore = keyStoreFromResource("clients/client.p12", password);
		KeyStore trustStore = keyStoreFromResource(
				"dev_and_test_truststore.p12", password);

		OkHttpClient httpClient = HttpClients
				.builder()
				.withClientCert(keyStore, password)
				.addRequestInterceptors(
						new AuthHelper.AcceptRequestInterceptor(
								MediaType.APPLICATION_JSON))
				.build(trustStore, 4444);
		ObjectMapper mapper = KeywhizService.customizeObjectMapper(Jackson
				.newObjectMapper());
		return new KeywhizClient(mapper, httpClient);

	}
```
