### ISSUE TITLE
I am unable to import as maven project into eclipse.

### ISSUE THREAD

**Issue by hshyamh4** [square/keywhiz#83]
Hi ,
Error is:

Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (execution: default-compile, phase: compile)	pom.xml	/keywhiz-testing	line 5	Maven Project Build Lifecycle Mapping Problem

But from command prompt It is working.

**Comment by sul3n3t** [comment]
I'm not an Eclipse user (prefer IntelliJ), but I tried selecting "Import" and "Existing Maven Projects". There were several "errors" including the one you posted and others of the form "no marketplace entries found to ...". I'm afraid I have no idea how to make Eclipse work more than I've tried. If you (or someone else) does, please contribute to this issue.

**Comment by hshyamh4** [comment]
![keywhiz-maven-issue](https://cloud.githubusercontent.com/assets/12181092/7874897/a7c43116-05d3-11e5-8285-6744b0e24634.png)

Please look at screen shot.

**Comment by sul3n3t** [comment]
I agree, that screenshot looks like the one I got from a fresh Eclipse download. I took a little time to search around related to this, but I'm not familiar enough with Eclipse and m2e.

**Comment by sul3n3t** [comment]
Doesn't seem to be a problem with the keywhiz project per-se, but how to load a maven project in Eclipse.
