### ISSUE TITLE
When i create secrete with one jceks file(by uploading),i can not my file in the UI.

### ISSUE THREAD

**Issue by hshyamh4** [square/keywhiz#84]
At the time of creating secrete i uploaded a file with somefile.jceks but i do not know whether file is uploaded or not into server and how to read this secrete along with somefile.jceks from java application.
Is there any certificate required ? how can i contact the server.

**Comment by sul3n3t** [comment]
I presume you created the new secret by uploading a file on the UI. When you navigate back to `/ui/#/secrets` it should be displayed there. It may require a page refresh, but I wouldn't expect it to.

To actually read the secret, you assign it to a client (back by a client certificate). KeywhizFs (or curl) can use the client cert to GET `/secret/somefile.jceks`.
