### ISSUE TITLE
Secure file transmission

### ISSUE THREAD

**Issue by hshyamh4** [square/keywhiz#88]
Hi,
 Is it possible to transmitting the secrete JCEKS file from server to deployed machines directly using keywhiz ?

**Comment by sul3n3t** [comment]
Certainly, it can be done with curl. The current API for accessing a secret is `GET /secret/<secret_name>`. Use a client certificate to authenticate the request. With curl, use `--cert` option and points to [client.pem](https://github.com/square/keywhiz-fs/blob/master/fixtures/client.pem).

**Comment by hshyamh4** [comment]
Thanks for your response,

using curl i can do it, but how to do it in java ?

**Comment by sul3n3t** [comment]
You can use the [keywhiz-client module](https://github.com/square/keywhiz/tree/master/client) from java or use it as an example.

There is a [wiki page](https://github.com/square/keywhiz/wiki/Development-and-test-key-material) on how we generated key material, including certificates. The [certstrap project](https://github.com/square/certstrap) may be helpful, but any PKI can be used.
