### ISSUE TITLE
How to convert encrypted secret into a file

### ISSUE THREAD

**Issue by hshyamh4** [square/keywhiz#96]
![screenshot from 2015-06-03 16 06 21](https://cloud.githubusercontent.com/assets/12181092/7958450/248cd206-0a0d-11e5-9dce-e9420d0e4515.png)

After uploading a file i am unable to see file in the UI after refreshing the page also.

but when i use below
curl --cert client.pem -k -H "Content-Type:application/json"   https://localhost:4444/automation/secrets/1

{"id":1,"name":"Test","secret":"zs7OzgAAAAIAAAAFAAAAAwAQY3licS5kYi4yMDE1MDQyNwAAAUz6otwbrO0ABXNyADNjb209yS2V5UHJvdGVjdG9yzVfKWecwu1MCAAB4cgAZamF2YXguY3J5cHRvLlNlYWxlZE9iamVjdD42PabDt1RwAgAEWwANZW5jb2RlZFBhcmFtc3QAAltCWwAQZW5jcnlwdGVkQ29udGVudHEAfgACTAAJcGFyYW1zQWxndAASTGphdmEvbGFuZy9TdHJpbmc7TAAHc2VhbEFsZ3EAfgADeHB1cgACW0Ks8xf.............................","secretLength":2474,"creationDate":"2015-06-03T10:32:17.834Z","groups":[],"isVersioned":false}

Have you used any encryption algorithm,if so how i can convert to file.

**Comment by sul3n3t** [comment]
The response type is [AutomationSecretResponse.java](https://github.com/square/keywhiz/blob/master/api/src/main/java/keywhiz/api/AutomationSecretResponse.java) and the `secret` column is the base64'ed content.
